SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/datapath.sv $(PWD)/control.sv $(PWD)/chip.sv $(PWD)/array.sv $(PWD)/pe.sv $(PWD)/bram.sv
TOPLEVEL = chip
MODULE = testbench

include $(shell cocotb-config --makefiles)/Makefile.sim